version: '3'
services:
  db:
    image: postgres:alpine
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: medical_appointment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  migrate:
    restart: on-failure
    image: medicalappointment_medical_apppointment
    working_dir: /medical-appointment/src
    command: alembic upgrade head
    volumes:
      - .:/medical-appointment
    env_file: api.env
    depends_on:
      - db

  medical_apppointment:
    build: .
    restart: on-failure
    command: sh -c "coverage run --omit="**migrations**,**tests**" -m unittest discover -s src -v && coverage report && python src/run.py"
    volumes:
      - .:/medical-appointment
    ports:
      - "8000:8000"
    env_file: api.env
    depends_on:
      - db
      - migrate
