version: '3'
services:
  medical_apppointment:
    restart: always
    build: .
    command: python src/run.py
    volumes:
      - .:/medical-appointment
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medical_apppointment
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
